

import "./globals.css";
import "@fontsource/inter/index.css";
import "@fontsource/roboto/index.css";
import Header from "../components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans antialiased" style={{ fontFamily: 'Inter, Roboto, sans-serif' }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
